### PR TITLE
cat cat cat cat cat cat cat cat cat cat cat cat

### PR DESCRIPTION
**Pull request by chick0**
meow?

### CODE REVIEW

**Comment by suusha1340** [comment]
repository-open-graph-template
# @

- 

- 

> [](url)
From 3142a819dbf17dc949bf63d8cffc976efe058550 Mon Sep 17 00:00:00 2001
From: chick_0 <64462443+chick0@users.noreply.github.com>
Date: Wed, 24 Jun 2020 14:32:39 +0900
Subject: [PATCH 1/3] cat cat cat cat cat cat cat cat cat cat cat cat

meow?
---
 modules/cat.py | 36 ++++++++++++++++++++++++++++++++++++
 1 file changed, 36 insertions(+)
 create mode 100644 modules/cat.py

diff --git a/modules/cat.py b/modules/cat.py
new file mode 100644
index 0000000..1664a53
--- /dev/null
+++ b/modules/cat.py
@@ -0,0 +1,36 @@
+# -*- coding: utf-8 -*-
+
+import aiohttp
+import discord
+
+PERMISSION = 6
+
+HELP = '"고양이", "야옹", "meow", "cat" 이라는 단어에 반응합니다.'
+
+
+class CatWorker:
+    def __init__(self, message):
+        self.message = message
+        
+    async def __get_cat(self):
+        async with aiohttp.ClientSession() as session:
+            async with session.get("https://aws.random.cat/meow") as resp:
+                return await resp.json()
+
+    async def send_cat(self, filtered, color=0xFCFCFC):
+        cat_data = await self.__get_cat()
+
+        embed = discord.Embed(title=f"{filtered}!", color=color)
+        embed.set_image(url=cat_data['file'].replace("\\", ''))
+        await self.message.channel.send(embed=embed)
+
+
+async def main(message):
+    if message.author.bot:
+        return
+
+    cat_filter = ["고양이", "야옹", "meow", "cat"]
+    for check in cat_filter:
+        if check in str(message.content).lower():
+            worker = CatWorker(message)
+            await worker.send_cat(check)

From d02e3d5e3ebf11fdb85ad51ac56f2179e3776967 Mon Sep 17 00:00:00 2001
From: chick_0 <64462443+chick0@users.noreply.github.com>
Date: Sun, 28 Jun 2020 23:56:15 +0900
Subject: [PATCH 2/3] cat cat cat cat cat cat cat cat cat cat cat cat

cat cat cat cat cat cat cat cat cat cat cat cat
---
 modules/cat.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/modules/cat.py b/modules/cat.py
index 1664a53..3ea9d07 100644
--- a/modules/cat.py
+++ b/modules/cat.py
@@ -14,7 +14,8 @@ def __init__(self, message):
         
     async def __get_cat(self):
         async with aiohttp.ClientSession() as session:
-            async with session.get("https://aws.random.cat/meow") as resp:
+            # 기존api(https://aws.random.cat/meow) 사망으로 자체 api로 변경
+            async with session.get("https://api.chick.ga/api") as resp:
                 return await resp.json()
 
     async def send_cat(self, filtered, color=0xFCFCFC):

From e14ff7e51e5b2bdb3375f7ddc40c1ed21f91d497 Mon Sep 17 00:00:00 2001
From: chick_0 <64462443+chick0@users.noreply.github.com>
Date: Sun, 28 Jun 2020 23:58:13 +0900
Subject: [PATCH 3/3] Update cat.py

---
 modules/cat.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/modules/cat.py b/modules/cat.py
index 3ea9d07..5728e49 100644
--- a/modules/cat.py
+++ b/modules/cat.py
@@ -14,7 +14,7 @@ def __init__(self, message):
         
     async def __get_cat(self):
         async with aiohttp.ClientSession() as session:
-            # 기존api(https://aws.random.cat/meow) 사망으로 자체 api로 변경
+            # 기존api(https://aws.random.cat/meow) 503에러로 인하여 자체 api로 변경
             async with session.get("https://api.chick.ga/api") as resp:
                 return await resp.json()
 #
Duplicate of #

**Comment by suusha1340** [comment]
diff --git a/modules/cat.py b/modules/cat.py
new file mode 100644
index 0000000..5728e49
--- /dev/null
+++ b/modules/cat.py
@@ -0,0 +1,37 @@
+# -*- coding: utf-8 -*-
+
+import aiohttp
+import discord
+
+PERMISSION = 6
+
+HELP = '"고양이", "야옹", "meow", "cat" 이라는 단어에 반응합니다.'
+
+
+class CatWorker:
+    def __init__(self, message):
+        self.message = message
+        
+    async def __get_cat(self):
+        async with aiohttp.ClientSession() as session:
+            # 기존api(https://aws.random.cat/meow) 503에러로 인하여 자체 api로 변경
+            async with session.get("https://api.chick.ga/api") as resp:
+                return await resp.json()
+
+    async def send_cat(self, filtered, color=0xFCFCFC):
+        cat_data = await self.__get_cat()
+
+        embed = discord.Embed(title=f"{filtered}!", color=color)
+        embed.set_image(url=cat_data['file'].replace("\\", ''))
+        await self.message.channel.send(embed=embed)
+
+
+async def main(message):
+    if message.author.bot:
+        return
+
+    cat_filter = ["고양이", "야옹", "meow", "cat"]
+    for check in cat_filter:
+        if check in str(message.content).lower():
+            worker = CatWorker(message)
+            await worker.send_cat(check)

**Comment by chick0** [comment]
?

**Comment by KokoseiJ** [comment]
Closing due to broken API server

**Comment by chick0** [comment]
UwU Looking for another api...

**Pull request closed without merging**
